import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navs/NavBar";
import Sidebar from "./components/navs/SideBar";
import Bottombar from "./components/navs/BottomBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-sec`}
      >
        {/* Navbar */}
        <Navbar />
        
        <div className=" lg:flex min-h-screen">
          <div className="lg:basis-1/6 h-full">
          <Sidebar />
          </div>
          
          {/* Main Content */}
          <main className="flex-grow p-4 bg-sec w-full lg:basis-5/6 ">{children}</main>
        </div>
        <Bottombar/>
      </body>
    </html>
  );
}
